### ISSUE TITLE
Cannot enter valid Integer type in /cold-framework endpoint

### ISSUE THREAD

**Issue by kmorcinek** [ArturWincenciak/Blef#50]
Entered Integer `12345` Is valid but I cannot sent the value through swagger, it is always red.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/1745689/188328422-9d7bfc3d-8f31-4723-bfce-89745b0e04cc.png">

**Comment by ArturWincenciak** [comment]
A restriction is defined for this property: the value must be in the range from 3 to 6. You can see it here: https://github.com/ArturWincenciak/Blef/blob/e2d6597987ac724bbae19ddd9f652e121c1d0910/src/Modules/Games/Blef.Modules.Games.Api/Controllers/ErrorHandlingPlaygroundController.cs#L17

**Comment by ArturWincenciak** [comment]
Here you can test the API much easier: https://github.com/ArturWincenciak/Blef/blob/main/scripts/vsc-http/Blef.http (using https://marketplace.visualstudio.com/items?itemName=humao.rest-client plugin)

**Comment by ArturWincenciak** [comment]
![image](https://user-images.githubusercontent.com/9107578/190848695-95fb83fe-553b-4f2a-812b-8cd5d464cc86.png)
