### ISSUE TITLE
Send card to player that connects to the game

### ISSUE THREAD

**Issue by kmorcinek** [ArturWincenciak/Blef#57]
Description in next comment

**Comment by ArturWincenciak** [comment]
# 1. Join to game using game's ID

## POST /games/{id}/players
### request
```json
{
     "playerId": 12345
}
```
### response
`201 Created`
```json
{ }
``` 
# 2. Get cards

## GET /games/{id}/players/{playerId}/cards
### response
`200 OK`
```json
{
    "cards": [
        {
            "faceCard": "Ace",
            "suit": "Diamonds"
        }
    ]
}
```

# 3. Bid or check poker hand (in that very first feature that means the game has been started now with all joined players, does not matter who and how many players already joined)

# 3.1. Bid

## POST /games/{id}/players/{playerId}/bids
### request
```json
{
    /* bids */
}
```
### response
`201 Created`
```json
{/* empty */}
```
`400 BadRequest`
```json
{
    /* probem details */ 
}
```

# 3.2. Check

## POST /games/{id}/players/{playerId}/checks
### request
```json
{/* empyt */}
```
### response
`201 Created`
```json
{
    "settlement": "win/lose"
}
```
`400 BadRequest`
```json
{
    /* probem details */ 
}
```
